Repository SickChill/sickchill, pull requests merged in 2022-07, with the labels that each got.

#7960 Update main.mako full screen
  sickchill/gui/slick/views/config_general.mako
  sickchill/gui/slick/views/layouts/main.mako
  sickchill/settings.py
  sickchill/start.py
  sickchill/views/config/general.py
Labels: Enhancement

#8028 Make lxml optional since html.xml parser in python3.7+ works...
  .github/workflows/pythonpackage.yml
  .github/workflows/upgrade_dependencies.yml
  pyproject.toml
  sickchill/gui/slick/js/core.js
  sickchill/gui/slick/js/core.min.js
  sickchill/oldbeard/bs4_parser.py
  sickchill/oldbeard/providers/horriblesubs.py
  sickchill/oldbeard/providers/limetorrents.py
  sickchill/oldbeard/providers/newnewznab.py
  sickchill/oldbeard/providers/torrentz.py
  sickchill/oldbeard/subtitles.py
  sickchill/start.py
  sickchill/views/config/providers.py
Labels: In Progress, Please test, Experiment, python

#8015 Add Show Year and bracket of year features
  sickchill/gui/slick/views/config_postProcessing.mako
  sickchill/settings.py
  sickchill/start.py
  sickchill/tv.py
  sickchill/views/config/post_processing.py
Labels: Enhancement, Feature, python
